- name: Deploy container for local Patroller node
  docker_container:
    name: "claims"
    state: "{{ 'started' if patroller_enabled|default(False)|bool else 'absent' }}"
    image: "{{patroller_image_version}}"
    env:
      PATROLLER_USER_LABELS: "ccc-user.email"
      PATROLLER_LEASE: "{{patroller_lease|string}}"
    labels:
      frp.enabled: "true"
      frp.80: "http"
      frp.80.health_check: "false"
      frp.80.http.subdomain: "{{ inventory_hostname }}-monitor"
      frp.80.http.username: "{{ patroller_secure.user }}"
      frp.80.http.password: "{{ patroller_secure.pass }}"
    exposed_ports: 80

    networks:
      - name: "{{patroller_network}}"
        aliases: ["claims", "reservation"]
      - name: "bridge"
      - name: "{{patroller_proxy_network}}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"      

    pid_mode: host
    privileged: True
    purge_networks: yes
    restart_policy: unless-stopped
    pull: yes
