- name: Deploy container for local Patroller node
  docker_container:
    name: "claims"
    state: "{{ 'started' if patroller_enabled|default(False)|bool else 'absent' }}"
    image: "{{patroller_image_version}}"
    env:
      PATROLLER_USER_LABELS: "ccc-user.email"
      PATROLLER_LEASE: "{{patroller_lease|string}}"
    labels:
      frp.enabled: "true"
      frp.80: "http"
      frp.80.health_check: "false"
      frp.80.http.subdomain: "{{ inventory_hostname }}-monitor"
      frp.80.http.username: "{{ patroller_secure.user }}"
      frp.80.http.password: "{{ patroller_secure.pass }}"
    exposed_ports: 80

    networks:
      - name: "{{patroller_network}}"
        aliases: ["claims", "reservation"]
      - name: "bridge"
      - name: "{{patroller_proxy_network}}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"      

    pid_mode: host
    privileged: True
    purge_networks: yes
    restart_policy: unless-stopped
    pull: yes
    log_driver: json-file
    log_options:
      max-size: 10m
      max-file: 5
      compress: True
      
- name: Setup config file for WebUI
  block:
    - name: Ensures /etc/patroller dir exists
      file: path=/etc/patroller state=directory
    
    - name: Write variables to json config  file
      copy: 
        content: "{{ patroller_webui_config | to_nice_json }}" 
        dest: /etc/patroller/web-ui.json
  when: patroller_webui|default(False)|bool

- name: Deploy container for WebUI Patroller node
  docker_container:
    name: "patroller-webui"
    state: "{{ 'started' if patroller_webui|default(False)|bool else 'absent' }}"
    image: "{{patroller_webui_image_version}}"
    env:
      STREAMLIT_SERVER_PORT: "80"
    labels:
      frp.enabled: "true"
      frp.80: "http"
      frp.80.health_check: "false"
      frp.80.http.subdomain: "patroller"
      frp.80.http.username: "{{ patroller_secure.user }}"
      frp.80.http.password: "{{ patroller_secure.pass }}"
    exposed_ports: 80
    networks:
      - name: "{{patroller_proxy_network}}"
    volumes:
      - "/etc/patroller/web-ui.json:/etc/patroller/web-ui.json"

    purge_networks: yes
    restart_policy: unless-stopped
    pull: yes
    log_driver: json-file
    log_options:
      max-size: 10m
      max-file: 5
      compress: True
