- name: Removing container {{ container.STACK_NAME }}
  community.docker.docker_container:
    name: "{{ container.STACK_NAME }}"
    state: absent
    keep_volumes: no
    purge_networks: yes
    
- name: Remove overlay network for {{ container.STACK_NAME }}
  community.docker.docker_network:
    name: "overlay-{{ container.STACK_NAME }}"
    state: absent
