##################################################################################################################################
##################################################################################################################################

- name: List current private data mounts for {{ container.USER_EMAIL }}
  ansible.builtin.find:
    path: "{{ mount_points.nfs.user_data }}/{{ container.USER_EMAIL }}/private"
    file_type: directory
    recurse: no
  register: CURRENT_PRIVATE_DATA_MOUNTS

- name: Removing any private data mounts for {{ container.USER_EMAIL }}
  ansible.posix.mount:
    path: "{{ mount_points.nfs.user_data }}/{{ container.USER_EMAIL }}/private/{{ item.path|basename }}"
    state: absent
  with_items: "{{ CURRENT_PRIVATE_DATA_MOUNTS.files }}"
  loop_control:
    label: "{{ item.path|basename }}"

- name: Find all files in remaining private data mounts {{ container.USER_EMAIL }}
  ansible.builtin.find:
    path: "{{ mount_points.nfs.user_data }}/{{ container.USER_EMAIL }}/private"
    file_type: directory
    recurse: no
  register: CURRENT_PRIVATE_DATA_MOUNTS_REMAINING

- name: Removing any empty left over dirs from private data mounts for {{ container.USER_EMAIL }}
  ansible.builtin.file:
    path: "{{ mount_points.nfs.user_data }}/{{ container.USER_EMAIL }}/private/{{ item.path|basename }}"
    state: absent
  with_items: "{{ CURRENT_PRIVATE_DATA_MOUNTS_REMAINING.files }}"
  when: item.isdir and item.size == 2
  loop_control:
    label: "{{ item.path|basename }}"

##################################################################################################################################
##################################################################################################################################

- name: Remove local HDD/SSD storage folders on worker node for {{ container.STACK_NAME }}
  file: 
    path: "{{ filepath }}"
    state: absent
    owner: "{{ nfs_user_name }}"
    group: "{{ nfs_user_name }}"
  with_items:
    - "{{ mount_points.local.hdd_data }}/{{ container.USER_EMAIL }}"
    - "{{ mount_points.local.ssd_data }}/{{ container.USER_EMAIL }}"
  loop_control: {loop_var: filepath}

##################################################################################################################################
##################################################################################################################################

- name: Remove dir for user files on NFS storage 
  file: 
    path: "{{ mount_points.nfs.user_data }}/{{ container.USER_EMAIL }}"
    state: absent
  become: True
  become_user: "{{ nfs_user_name }}"
  run_once: true # NOTE: only run once on any of the hosts since this will write to the same shared storage

