# Deploy compute-container for each entry in config/user-containers.yml
- hosts: "{{ machines }}"
  become: yes
  become_user: root
  tasks: 

    - set_fact: process_index={{process_index|default(0)}}
    - set_fact: process_total={{process_total|default(1)}}    

    # For every running container do:
    #  1. Get MAC address of its primary network (from docker inspect)
    #  2. Find network name by matching it to /sys/class/net/*/address
    #  3. Collect rx and tx from network in container
    #  4. Save value to file
    
    - name: Select containers for usage check
      vars: 
        container: "{{ deployment_users[container_iter.USER_EMAIL] | default({}) | combine(container_iter) }}"
      set_fact: 
        selected_deployment_containers: "{{ selected_deployment_containers|default([]) + [ container ] }}"
      with_items: "{{ deployment_containers }}"
      loop_control: 
        loop_var: container_iter
      when:
         (containers is not defined and users is not defined) or
         (containers is defined and container_iter.STACK_NAME in containers.split(",")) or
         (users is defined and deployment_users[container_iter.USER_EMAIL].USER_EMAIL in users.split(","))
      no_log: True
      
    - name: Collect statistics from each running container
      vars: 
        container: "{{ container_iter }}"
      include_tasks: tasks/container-collect-network-stat.yml
      with_items: "{{ selected_deployment_containers }}"      
      loop_control: 
        loop_var: container_iter
        index_var: iter
      when: "{{ iter|int % process_total|int == process_index|int }}"