- name: install nvidia if requested
  when: nvidia_enabled|bool
  block:  
  - name: Add repo for proprietary nvidia drivers
    apt_repository:
      repo: ppa:graphics-drivers/ppa
      state: present
  
  - name: Gather package facts
    package_facts:
      manager: auto
    
  - name: Removing previous nvidia-driver version before installing new version
    apt: 
      update_cache: yes
      install_recommends: no
      name: ["nvidia-headless-*", "nvidia-utils-*", "nvidia-compute-utils-*", "nvidia-dkms-*", "nvidia-kernel-common-*", "nvidia-kernel-source-*"] 
      state: absent
      purge: yes
    when: '"nvidia-headless-{{nvidia_driver_version}}" not in ansible_facts.packages or "nvidia-utils-{{nvidia_driver_version}}" not in ansible_facts.packages'
    
  - name: Update apt and install nvidia-driver
    apt: 
      update_cache: yes
      install_recommends: no
      name: ["nvidia-headless-{{nvidia_driver_version}}", "nvidia-utils-{{nvidia_driver_version}}"] 
      state: present
    register: aptkey
    
  - name: Install service that will put GPUs into the presistent mode at startup time (default service does not)
    template: src=nvidia-persistenced.service dest=/lib/systemd/system/nvidia-persistenced.service
    
  - name: reboot machine if new driver installed
    reboot:
    when: aptkey.changed 
  
  - name: Reload nvidia-persistenced.service
    systemd:    
      name: nvidia-persistenced.service
      state: restarted
      daemon_reload: yes
    when: aptkey.changed
  
  - name: Prevent unattended updates for nvidia drivers
    lineinfile:
      path: /etc/apt/apt.conf.d/50unattended-upgrades
      line: '        "nvidia-*";'
      insertafter: "Unattended-Upgrade::Package-Blacklist {"
      firstmatch: yes
      create: no
    ignore_errors: yes # do not complain if file does not exist
