- name: install mellanox OFED driver if requested
  when: mellanox_enabled|bool
  block:  
    - name: Adding Mellanox GPG key
      apt_key: url=https://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox

    - name: Adding repo to /etc/apt/sources.list.d/
      get_url:
        dest: /etc/apt/sources.list.d/
        url: "https://linux.mellanox.com/public/repo/mlnx_ofed/latest/ubuntu{{ ansible_distribution_version }}/mellanox_mlnx_ofed.list"

    
    - name: Check if mlnx-ofed-all is installed
      stat:
        path: /usr/sbin/ofed_uninstall.sh
      register: mlnx_ofed_all_installed
      failed_when: false

    - name: Remove incompatible packages
      apt:
        name:
          - libipathverbs1
          - librdmacm1
          - libibverbs1
          - libmthca1
          - libopenmpi-dev
          - openmpi-bin
          - openmpi-common
          - openmpi-doc
          - libmlx4-1
          - rdmacm-utils
          - ibverbs-utils
          - infiniband-diags
          - ibutils
          - perftest
        state: absent
        update_cache: yes 
      when: not mlnx_ofed_all_installed.stat.exists
    
    - name: Install mellanox OFED driver
      apt:
        name:
          - mlnx-ofed-all
          - mlnx-fw-updater
        state: present
        update_cache: yes 
      register: mlnx_ofed_newly_installed
      
    - name: Restart /etc/init.d/openibd after new install
      service:
        name: openibd
        state: restarted
      when: mlnx_ofed_newly_installed|changed

      
        

    
    