# NOTE: 
#  - mapping between access and network can be defined in group_vars/ccc-cluster/cluster-vars.yml (see 'compute_container_networks' variable)
#  - compute groups can be defined in host specific files in 'compute_devices' var (e.g., see host_vars/node1.yml)

deployment_types:
  student: 
    access: restricted
    default_nodes: ['node3'] 
    allowed_nodes: ['node3'] 
    allowed_device_groups: ['device_student']
  researcher: 
    access: unlimited
    default_nodes: ['node1']
    allowed_nodes: ['node1','node2','node3']
    allowed_device_groups: ['device_lab']

deployment_users:
  yourname@email.com:
    USER_FULLNAME: Your Name
    USER_EMAIL: yourname@email.com
    USER_NAME: username
    USER_PUBKEY: ""
    USER_PUBKEY_FROM_GITHUB: github_username
    USER_TYPE: researcher
    ADDITIONAL_DEVICE_GROUPS: ['device_student']
