- name: Install docker 
  import_tasks: install-docker.yml

- name: Install nvidia plugin if required
  import_tasks: install-nvidia-docker.yml
  when: docker_nvidia_plugin|bool
  
- name: Login to repositiroies
  import_tasks: login-repository.yml

- name: Deploy docker swarm
  import_tasks: deploy-swarm.yml
  when: docker_swarm_enabled|bool

- name: Deploy networks
  import_tasks: deploy-networks.yml
  
