deployment_containers:
#  - STACK_NAME: container-name
#    STORAGE_NAME: container-name
#    USER_EMAIL: user@email.com
#    CONTAINER_IMAGE: vicoslab/ccc:base-ubuntu18.04-cuda10.1
#    DEPLOYMENT_NODES: ['lab_node1','lab_node2']
#    INSTALL_PACKAGES: "nano htop zip unzip rar unrar openjdk-8-jdk"
#    RUN_PRIVILEGED: False
#    SHM_SIZE: 2GB
#    FRP_PORTS:
#      TCP: [22,]
#      HTTP: 
#        - { port: "6006", subdomain: "<http-subdomain>", pass: "<http-pass>", health_check: "false", subdomain_hostname_prefix: true }
#    ADDITIONAL_DEVICE_GROUPS: []

deployment_types:
#  student: 
#    network_access: restricted
#    default_nodes: ['student_node1']
#    allowed_nodes: ['student_node1','student_node2','student_node3'] 
#    allowed_device_groups: ['students']
#  researcher: 
#    network_access: unrestricted
#    default_nodes: ['lab_node1']
#    allowed_nodes: ['lab_node1','lab_node2','lab_node3'] 
#    allowed_device_groups: ['lab']


deployment_users:
#  user@email.com:
#    USER_FULLNAME: Your Name
#    USER_EMAIL: user@email.com
#    USER_NAME: <username>
#    USER_PUBKEY: <openssh-public-key>
#    USER_PUBKEY_FROM_GITHUB: <optional-github-username>
#    USER_TYPE: researcher

mount_points:
  nfs:
#    user_data: ''
#    group_data: ''
#    apps_data: ''
#    dataset_data: ''
  local:
#    hdd_data: ''
#    ssd_data: ''
#    sshd_data: ''

compute_container_apps:
#  - '/usr/local/bin/YOUR_APP'
#  - '/usr/local/bin/YOUR_SECOND_APP'

compute_container_networks:
#  restricted: [ { name: "network1" }, { name: "shared_network"} ]
#  unrestricted: [ {name: "network2" }, { name: "shared_network"} ]

compute_devices:
#  students: ['GPUID1','GPUID2']
#  lab: ['GPUID3','GPUID4']
