compute_container_nightwatch: False
compute_container_nightwatch_git_url: ""
compute_container_nightwatch_git_branch: master
compute_container_nightwatch_git_intentory_dir: inventory
compute_container_nightwatch_git_playbook_dir: playbook

compute_container_nightwatch_secure:
  git_token: ""
